/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    DescriptorIndexResponse,
    DescriptorIndexResponseFromJSON,
    DescriptorIndexResponseToJSON,
} from '../models';

/**
 * 
 */
export class DescriptorApi extends runtime.BaseAPI {

    /**
     * Index
     */
    async descriptorControllerIndexRaw(): Promise<runtime.ApiResponse<DescriptorIndexResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/descriptor`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => DescriptorIndexResponseFromJSON(jsonValue));
    }

    /**
     * Index
     */
    async descriptorControllerIndex(): Promise<DescriptorIndexResponse> {
        const response = await this.descriptorControllerIndexRaw();
        return await response.value();
    }

}
