/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface FeedControllerImportRequest {
    session: string;
    body?: any | null;
}

/**
 * 
 */
export class FeedApi extends runtime.BaseAPI {

    /**
     * Import
     */
    async feedControllerImportRaw(requestParameters: FeedControllerImportRequest): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.session === null || requestParameters.session === undefined) {
            throw new runtime.RequiredError('session','Required parameter requestParameters.session was null or undefined when calling feedControllerImport.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/feed/{session}/import`.replace(`{${"session"}}`, encodeURIComponent(String(requestParameters.session))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.body as any,
        });

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Import
     */
    async feedControllerImport(requestParameters: FeedControllerImportRequest): Promise<void> {
        await this.feedControllerImportRaw(requestParameters);
    }

}
