/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DescriptorTemplateResponse
 */
export interface DescriptorTemplateResponse {
    /**
     * 
     * @type {string}
     * @memberof DescriptorTemplateResponse
     */
    content: string;
}

export function DescriptorTemplateResponseFromJSON(json: any): DescriptorTemplateResponse {
    return DescriptorTemplateResponseFromJSONTyped(json, false);
}

export function DescriptorTemplateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DescriptorTemplateResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'content': json['content'],
    };
}

export function DescriptorTemplateResponseToJSON(value?: DescriptorTemplateResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'content': value.content,
    };
}


