/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MeasurementQuery
 */
export interface MeasurementQuery {
    /**
     * 
     * @type {number}
     * @memberof MeasurementQuery
     */
    session: number;
    /**
     * 
     * @type {number}
     * @memberof MeasurementQuery
     */
    timestamp: number;
    /**
     * 
     * @type {boolean}
     * @memberof MeasurementQuery
     */
    forward: boolean;
}

export function MeasurementQueryFromJSON(json: any): MeasurementQuery {
    return MeasurementQueryFromJSONTyped(json, false);
}

export function MeasurementQueryFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeasurementQuery {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'session': json['session'],
        'timestamp': json['timestamp'],
        'forward': json['forward'],
    };
}

export function MeasurementQueryToJSON(value?: MeasurementQuery | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'session': value.session,
        'timestamp': value.timestamp,
        'forward': value.forward,
    };
}


