/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SessionPaperResponse
 */
export interface SessionPaperResponse {
    /**
     * 
     * @type {string}
     * @memberof SessionPaperResponse
     */
    context: string;
}

export function SessionPaperResponseFromJSON(json: any): SessionPaperResponse {
    return SessionPaperResponseFromJSONTyped(json, false);
}

export function SessionPaperResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionPaperResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'context': json['context'],
    };
}

export function SessionPaperResponseToJSON(value?: SessionPaperResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'context': value.context,
    };
}


