/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SessionPaperCommand
 */
export interface SessionPaperCommand {
    /**
     * 
     * @type {string}
     * @memberof SessionPaperCommand
     */
    context: string;
}

export function SessionPaperCommandFromJSON(json: any): SessionPaperCommand {
    return SessionPaperCommandFromJSONTyped(json, false);
}

export function SessionPaperCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionPaperCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'context': json['context'],
    };
}

export function SessionPaperCommandToJSON(value?: SessionPaperCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'context': value.context,
    };
}


