/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SessionRealResponse
 */
export interface SessionRealResponse {
    /**
     * 
     * @type {string}
     * @memberof SessionRealResponse
     */
    context: string;
}

export function SessionRealResponseFromJSON(json: any): SessionRealResponse {
    return SessionRealResponseFromJSONTyped(json, false);
}

export function SessionRealResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionRealResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'context': json['context'],
    };
}

export function SessionRealResponseToJSON(value?: SessionRealResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'context': value.context,
    };
}


