/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SessionUniverseResponse
 */
export interface SessionUniverseResponse {
    /**
     * 
     * @type {Array<any>}
     * @memberof SessionUniverseResponse
     */
    instruments: Array<any>;
}

export function SessionUniverseResponseFromJSON(json: any): SessionUniverseResponse {
    return SessionUniverseResponseFromJSONTyped(json, false);
}

export function SessionUniverseResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionUniverseResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'instruments': json['instruments'],
    };
}

export function SessionUniverseResponseToJSON(value?: SessionUniverseResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'instruments': value.instruments,
    };
}


