/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface EventControllerConnectRequest {
    context?: string;
}

/**
 * 
 */
export class EventApi extends runtime.BaseAPI {

    /**
     * Connect
     */
    async eventControllerConnectRaw(requestParameters: EventControllerConnectRequest): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters.context !== undefined) {
            queryParameters['context'] = requestParameters.context;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/event`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Connect
     */
    async eventControllerConnect(requestParameters: EventControllerConnectRequest): Promise<void> {
        await this.eventControllerConnectRaw(requestParameters);
    }

}
