/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MeasureResponse
 */
export interface MeasureResponse {
    /**
     * 
     * @type {number}
     * @memberof MeasureResponse
     */
    timestamp: number;
    /**
     * 
     * @type {string}
     * @memberof MeasureResponse
     */
    type: string;
}

export function MeasureResponseFromJSON(json: any): MeasureResponse {
    return MeasureResponseFromJSONTyped(json, false);
}

export function MeasureResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeasureResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'timestamp': json['timestamp'],
        'type': json['type'],
    };
}

export function MeasureResponseToJSON(value?: MeasureResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'timestamp': value.timestamp,
        'type': value.type,
    };
}


