/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SessionBacktestCommand
 */
export interface SessionBacktestCommand {
    /**
     * 
     * @type {number}
     * @memberof SessionBacktestCommand
     */
    from: number;
    /**
     * 
     * @type {number}
     * @memberof SessionBacktestCommand
     */
    to: number;
    /**
     * 
     * @type {string}
     * @memberof SessionBacktestCommand
     */
    context: string;
}

export function SessionBacktestCommandFromJSON(json: any): SessionBacktestCommand {
    return SessionBacktestCommandFromJSONTyped(json, false);
}

export function SessionBacktestCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionBacktestCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'from': json['from'],
        'to': json['to'],
        'context': json['context'],
    };
}

export function SessionBacktestCommandToJSON(value?: SessionBacktestCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'from': value.from,
        'to': value.to,
        'context': value.context,
    };
}


