name: publish

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - run: yarn
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
      - run: yarn run bump-apply
      - run: yarn run build
      - run: yarn run test:unit
      - run: yarn run publish
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: yarn run bump
