name: deploy

on:
  push:
    branches:
      - main

jobs:
  code-quality-gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.organization=quantform
            -Dsonar.projectKey=quantform_quantform
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  test-gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - run: yarn
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
      - run: yarn run test:unit

  publish-to-npm:
    needs: ['test-gate', 'code-quality-gate']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - run: yarn
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
      - run: npm version 0.3.${{ github.run_number }} --no-git-tag-version
      - run: npm version 0.3.${{ github.run_number }} --no-git-tag-version
        working-directory: ./packages/core
      - run: npm version 0.3.${{ github.run_number }} --no-git-tag-version
        working-directory: ./packages/storage/sqlite
      - run: npm version 0.3.${{ github.run_number }} --no-git-tag-version
        working-directory: ./packages/adapter/binance
      - run: npm version 0.3.${{ github.run_number }} --no-git-tag-version
        working-directory: ./packages/adapter/binance-future
      - run: npm version 0.3.${{ github.run_number }} --no-git-tag-version
        working-directory: ./packages/adapter/binance-delivery
      - run: npm version 0.3.${{ github.run_number }} --no-git-tag-version
        working-directory: ./packages/adapter/dukascopy
      - run: npm version 0.3.${{ github.run_number }} --no-git-tag-version
        working-directory: ./packages/adapter/oanda
      - run: npm version 0.3.${{ github.run_number }} --no-git-tag-version
        working-directory: ./packages/adapter/uniswap
      - run: npm version 0.3.${{ github.run_number }} --no-git-tag-version
        working-directory: ./packages/adapter/xtb
      - run: yarn run build
      - run: yarn run publish
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
