name: release

on:
  push:
    branches:
      - main
      - feature/new-cli
    tags:
      - v*

jobs:
  packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - run: yarn
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
      - run: yarn run build
      - run: yarn run test:unit
      - run: yarn workspaces foreach npm publish
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
