name: release

on:
  push:
    branches:
      - main
      - feature/new-cli
    tags:
      - v*

jobs:
  packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - run: yarn
      #- run: yarn run test:unit
      - run: yarn workspaces foreach version --new-version 0.1.${{ github.run_number }} --no-git-tag-version
      - run: yarn run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
