name: deploy

on:
  push:
    branches:
      - main

jobs:
  code-quality-gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.organization=quantform
            -Dsonar.projectKey=quantform_quantform
            -Dsonar.sources="."
            -Dsonar.tests="."
            -Dsonar.test.inclusions="**/*.spec.ts"
            -Dsonar.javascript.lcov.reportPaths="./packages/core/coverage/lcov.info"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  test-gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - run: yarn
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
          YARN_CHECKSUM_BEHAVIOR: update
      - run: yarn run build
      - run: yarn run test

  publish-to-npm:
    needs: ['test-gate', 'code-quality-gate']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - run: yarn
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
          YARN_CHECKSUM_BEHAVIOR: update
      - run: npm version 0.5.${{ github.run_number }} --no-git-tag-version
      - run: npm version 0.5.${{ github.run_number }} --no-git-tag-version
        working-directory: ./packages/core
      - run: npm version 0.5.${{ github.run_number }} --no-git-tag-version
        working-directory: ./packages/studio
      - run: npm version 0.5.${{ github.run_number }} --no-git-tag-version
        working-directory: ./packages/storage/sqlite
      - run: npm version 0.5.${{ github.run_number }} --no-git-tag-version
        working-directory: ./packages/adapter/binance
      - run: npm version 0.5.${{ github.run_number }} --no-git-tag-version
        working-directory: ./packages/adapter/dydx
      - run: yarn run build
      - run: yarn run publish
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
