name: publish-beta

on:
  push:
    branches:
      - develop

jobs:
  test-gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.11.0

      - name: Install dependencies
        run: pnpm install

      - name: Build core package
        run: pnpm run build
        working-directory: ./packages/core
      - name: Build sqlite package
        run: pnpm run build
        working-directory: ./packages/sqlite
      - name: Build binance package
        run: pnpm run build
        working-directory: ./packages/binance

      - name: Test core package
        run: pnpm run test
        working-directory: ./packages/core
      - name: Test sqlite package
        run: pnpm run test
        working-directory: ./packages/sqlite
      - name: Test binance package
        run: pnpm run test
        working-directory: ./packages/binance

  publish-to-npm:
    needs: ['test-gate']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.11.0
        
      - run: npx --yes json -I -f package.json -e "this.version='0.7.0-beta.${{ github.run_number }}'"
      - run: npx --yes json -I -f package.json -e "this.version='0.7.0-beta.${{ github.run_number }}'"
        working-directory: ./packages/core
      - run: npx --yes json -I -f package.json -e "this.version='0.7.0-beta.${{ github.run_number }}'"
        working-directory: ./packages/sqlite
      - run: npx --yes json -I -f package.json -e "this.version='0.7.0-beta.${{ github.run_number }}'"
        working-directory: ./packages/binance

      - name: Set npm token
        run: pnpm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}

      - name: Install dependencies
        run: pnpm install
        
      - name: Build package
        run: pnpm --filter core --filter sqlite --filter binance run build

      - name: Publish package
        run: pnpm publish --tag beta --no-git-checks
        working-directory: ./packages/core
      - name: Publish sqlite package
        run: pnpm publish --tag beta --no-git-checks
        working-directory: ./packages/sqlite
      - name: Publish binance package
        run: pnpm publish --tag beta --no-git-checks
        working-directory: ./packages/binance

