name: release

on:
  push:
    branches:
      - main

jobs:
  test-gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - uses: pnpm/action-setup@v4
        with:
          version: 9.5.0

      - name: Install dependencies
        run: pnpm install
        
      - name: Build core package
        run: pnpm run build
        working-directory: ./packages/core
      - name: Build sqlite package
        run: pnpm run build
        working-directory: ./packages/sqlite
      - name: Build binance package
        run: pnpm run build
        working-directory: ./packages/binance
      - name: Build ethereum package
        run: pnpm run build
        working-directory: ./packages/ethereum
      - name: Build hyperliquid package
        run: pnpm run build
        working-directory: ./packages/hyperliquid
      - name: Build telegram package
        run: pnpm run build
        working-directory: ./packages/telegram

      - name: Test core package
        run: pnpm run test
        working-directory: ./packages/core
      - name: Test sqlite package
        run: pnpm run test
        working-directory: ./packages/sqlite
      - name: Test binance package
        run: pnpm run test
        working-directory: ./packages/binance
      - name: Test ethereum package
        run: pnpm run test
        working-directory: ./packages/ethereum

  publish-to-npm:
    needs: ['test-gate']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - uses: pnpm/action-setup@v4
        with:
          version: 8.3.1
        
      - run: npx --yes json -I -f package.json -e "this.version='0.7.${{ github.run_number }}'"
      - run: npx --yes json -I -f package.json -e "this.version='0.7.${{ github.run_number }}'"
        working-directory: ./packages/core
      - run: npx --yes json -I -f package.json -e "this.version='0.7.${{ github.run_number }}'"
        working-directory: ./packages/sqlite
      - run: npx --yes json -I -f package.json -e "this.version='0.7.${{ github.run_number }}'"
        working-directory: ./packages/binance
      - run: npx --yes json -I -f package.json -e "this.version='0.7.${{ github.run_number }}'"
        working-directory: ./packages/ethereum
      - run: npx --yes json -I -f package.json -e "this.version='0.7.${{ github.run_number }}'"
        working-directory: ./packages/hyperliquid
      - run: npx --yes json -I -f package.json -e "this.version='0.7.${{ github.run_number }}'"
        working-directory: ./packages/telegram
      - run: npx --yes json -I -f package.json -e "this.version='0.7.${{ github.run_number }}'"
        working-directory: ./packages/create

      - name: Set npm token
        run: pnpm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Build all packages
        run: pnpm run build

      - name: Publish package
        run: pnpm publish --no-git-checks
        working-directory: ./packages/core
      - name: Publish sqlite package
        run: pnpm publish --no-git-checks
        working-directory: ./packages/sqlite
      - name: Publish binance package
        run: pnpm publish --no-git-checks
        working-directory: ./packages/binance
      - name: Publish ethereum package
        run: pnpm publish --no-git-checks
        working-directory: ./packages/ethereum
      - name: Publish hyperliquid package
        run: pnpm publish --no-git-checks
        working-directory: ./packages/hyperliquid
      - name: Publish telegram package
        run: pnpm publish --no-git-checks
        working-directory: ./packages/telegram
      - name: Publish create package
        run: pnpm publish --no-git-checks
        working-directory: ./packages/create

