name: validate

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - uses: pnpm/action-setup@v4
        with:
          version: 9.5.0
        
      - name: Install dependencies
        run: pnpm install
        
      - name: Build core package
        run: pnpm run build
        working-directory: ./packages/core
      - name: Build sqlite package
        run: pnpm run build
        working-directory: ./packages/sqlite
      - name: Build binance package
        run: pnpm run build
        working-directory: ./packages/binance

      - name: Test core package
        run: pnpm run test
        working-directory: ./packages/core
      - name: Test sqlite package
        run: pnpm run test
        working-directory: ./packages/sqlite
      - name: Test binance package
        run: pnpm run test
        working-directory: ./packages/binance