name: validate

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 6.0.2

      - name: Install dependencies
        run: pnpm install
        
      - name: Build all packages
        run: pnpm run build

      - name: Test all packages
        run: pnpm run test